Repository Henriknn01/wave-industries, pull requests merged in 2022-12, with the labels that each got.

#52 Big update
  waveBackend/BackendServices/ship_simulator.py
  waveBackend/waveAPI/models.py
  waveBackend/waveAPI/serializers.py
  waveBackend/waveAPI/urls.py
  waveBackend/waveAPI/views.py
  waveBackend/waveBackend/settings.py
Labels: development

#53 Frontend update
  waveBackend/BackendServices/ship_simulator.py
  wave_frontend/package-lock.json
  wave_frontend/package.json
  wave_frontend/src/components/AdminNavBar.vue
  wave_frontend/src/components/LiveStatsCard.vue
  wave_frontend/src/components/NavBar.vue
  wave_frontend/src/main.js
  wave_frontend/src/views/DashboardView.vue
  wave_frontend/src/views/ShipDashboardView.vue
  wave_frontend/yarn.lock
Labels: development

#54 added Section 2 rough, added certs and mosquitto.conf
  README.md
  documentation/firstDraft.pdf
  waveBackend/BackendServices/MQTT/BrokerConfig/certs/broker/broker.crt
  waveBackend/BackendServices/MQTT/BrokerConfig/certs/broker/broker.key
  waveBackend/BackendServices/MQTT/BrokerConfig/certs/ca/ca.crt
  waveBackend/BackendServices/MQTT/BrokerConfig/certs/ca/ca.key
  waveBackend/BackendServices/MQTT/BrokerConfig/certs/ca/ca.srl
  waveBackend/BackendServices/MQTT/BrokerConfig/certs/client/client.crt
  waveBackend/BackendServices/MQTT/BrokerConfig/certs/client/client.csr
  waveBackend/BackendServices/MQTT/BrokerConfig/certs/client/client.key
  waveBackend/BackendServices/MQTT/BrokerConfig/logs/mosquitto.log
  waveBackend/BackendServices/MQTT/BrokerConfig/mosquitto.conf
Labels: documentation

#57 fixed mqtt bug | added heading
  waveBackend/BackendServices/ship_simulator.py
Labels: bug, development

#62 fixed mqtt bugs | added db setup script
  waveBackend/BackendServices/mqtt-http-client.py
  waveBackend/BackendServices/ship_simulator.py
  waveBackend/BackendServices/test_db_init.py
Labels: development

#66 Adding Section II and III to the documentation
  README.md
  images/traffic.png
Labels: documentation

#69 Added section 6.i to the documentation
  README.md
Labels: documentation

#70 Added section 6.iiii to the documentation
  README.md
Labels: documentation

#73 Update README.md
  README.md
Labels: documentation

#74 Frontend rest api connection
  waveBackend/README.md
  waveBackend/waveAPI/serializers.py
  wave_frontend/src/components/LiveStatsCard.vue
  wave_frontend/src/components/MaintenanceCard.vue
  wave_frontend/src/components/RadialChartBasic.vue
  wave_frontend/src/main.js
  wave_frontend/src/views/ShipDashboardView.vue
Labels: bug, development

#77 final proof read,
  README.md
  images/logogif.gif
Labels: documentation

#78 updated requirements.txt
  waveBackend/requirements.txt
Labels: development
